(in-package :cl-rogue)

(eval-when (compile load)
  (proclaim '(optimize (debug 3) (safety 3))))

;; may have to run this by hand in the repl...
(declaim (optimize (debug 3) (safety 3)))

(defun compile-n-load (path)
  (compile-file path)
  (load path))

(load "/Users/jacob/cvsdude/project/cl-rogue/rogue.lisp") ; bootstrap
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/rogue")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/vers")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/init")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/io")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/main")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/armor")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/chase")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/command")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/daemon")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/daemons")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/fight")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/misc")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/monsters")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/move")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/newlevel")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/options")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/pack")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/package")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/passages")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/potions")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/rings")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/rip")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/rogue")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/rooms")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/scrolls")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/sticks")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/things")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/weapons")
(compile-n-load "/Users/jacob/cvsdude/project/cl-rogue/wizard")
